apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-dtp-pod
  namespace: {{ .Release.Namespace }}
  labels:
    app: DTP
spec:
  volumes:
{{- if .Values.persistence.name }}
    - name: dtp-data
      persistentVolumeClaim:
        claimName: {{ .Values.persistence.name }}
{{- end }}
{{- if .Values.deployment.customKeystore.enabled }}
    - name: keystore-cfgmap-volume
      configMap:
        name: {{ .Values.deployment.customKeystore.cfgMapName }}
{{- end }}
{{- if .Values.deployment.customTruststore.enabled }}
    - name: truststore-cfgmap-volume
      configMap:
        name: {{ .Values.deployment.customTruststore.cfgMapName }}
{{- end }}
  securityContext:
    runAsNonRoot: true
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault   
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: PARASOFT_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PARASOFT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- range $key, $val := .Values.deployment.envVarsDtp }}
        - name: {{ $key }}
          value: {{ $val | quote }}
{{- end }}
{{- if .Values.deployment.db.type }}
        - name: DB_TYPE
          value: {{ .Values.deployment.db.type }}
{{- end }}
{{- if .Values.deployment.db.user }}
        - name: DB_USER
          value: {{ .Values.deployment.db.user }}
{{- end }}
{{- if and (.Values.deployment.db.passwordSecret) (.Values.deployment.db.passwordSecretKey) }}
        - name: DB_PASSWORD
          value: "root1234"
{{- end }}
{{- if .Values.deployment.db.url }}
        - name: DB_URL
          value: {{ .Values.deployment.db.url }}
{{- end }}
{{- if .Values.deployment.db.jdbcDriverUrl }}
        - name: JDBC_DRIVER_URL
          value: {{ .Values.deployment.db.jdbcDriverUrl }}
{{- end }}
{{- if .Values.deployment.jvmArgsDtp.enabled }}
        - name: JAVA_CONFIG_ARGS
          value: {{ .Values.deployment.jvmArgsDtp.value }}
{{- end }}
      args: ["--run", "dtp"]
      ports:
        - name: "http-server"
          containerPort: 8080
        - name: "https-server"
          containerPort: 8443
      volumeMounts:
{{- if .Values.persistence.name }}
        - name: dtp-data
          mountPath: "/usr/local/parasoft/data"
{{- end }}
{{- if .Values.deployment.customKeystore.enabled }}
        - name: keystore-cfgmap-volume
          mountPath: "/usr/local/parasoft/dtp/tomcat/conf/.keystore"
          subPath: {{ .Values.deployment.customKeystore.keystoreSubPath }}
        - name: keystore-cfgmap-volume
          mountPath: "/usr/local/parasoft/dtp/tomcat/conf/server.xml"
          subPath: {{ .Values.deployment.customKeystore.serverCfgSubPath }}
{{- end }}
{{- if .Values.deployment.customTruststore.enabled }}
        - name: truststore-cfgmap-volume
          mountPath: "/usr/local/parasoft/dtp/jre/lib/security/cacerts"
          subPath: {{ .Values.deployment.customTruststore.truststoreSubPath }}
{{- end }}
{{- if .Values.deployment.healthcheck.enabled }}
      livenessProbe:
        exec:
          command:
          - healthcheck.sh
          - --verify
          - dtp
        initialDelaySeconds: 120
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 5
{{- end }}
    - name: {{ .Chart.Name }}-data-collector
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault   
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
{{- range $key, $val := .Values.deployment.envVarsDc }}
        - name: {{ $key }}
          value: {{ $val | quote }}
{{- end }}
{{- if .Values.deployment.jvmArgsDc.enabled }}
        - name: JAVA_DC_CONFIG_ARGS
          value: {{ .Values.deployment.jvmArgsDc.value }}
{{- end }}
      args: ["--run", "datacollector", "--no-copy-data"]
      ports:
        - name: "dc-server"
          containerPort: 8082
      volumeMounts:
{{- if .Values.persistence.name }}
        - name: dtp-data
          mountPath: "/usr/local/parasoft/data"
{{- end }}
{{- if .Values.deployment.healthcheck.enabled }}
      livenessProbe:
        exec:
          command:
          - healthcheck.sh
          - --verify
          - datacollector
        initialDelaySeconds: 120
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 5
{{- end }}
{{- if .Values.deployment.extensionDesigner.enabled }}
    - name: {{ .Chart.Name }}-extension-designer
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
{{- range $key, $val := .Values.deployment.extensionDesigner.envVars }}
        - name: {{ $key }}
          value: {{ $val | quote }}
{{- end }}
{{- if .Values.deployment.extensionDesigner.externalMongoDb.enabled }}
        - name: DEP_USE_REMOTE_DB
          value: {{ .Values.deployment.extensionDesigner.externalMongoDb.enabled | quote }}
        - name: DEP_DB_HOSTNAME
          value: {{ .Values.deployment.extensionDesigner.externalMongoDb.hostname }}
        - name: DEP_DB_PORT
          value: {{ .Values.deployment.extensionDesigner.externalMongoDb.port | quote }}
{{- end }}
      args: ["--run", "dtpservices"]
      ports:
        - name: "dep-server"
          containerPort: 8314
      volumeMounts:
{{- if .Values.persistence.name }}
        - name: dtp-data
          mountPath: "/usr/local/parasoft/data"
{{- end }}
{{- if .Values.deployment.healthcheck.enabled }}
      livenessProbe:
        exec:
          command:
          - healthcheck.sh
          - --verify
          - dtpservices
        initialDelaySeconds: 120
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 5
{{- end }}
{{- end }}
  restartPolicy: {{ .Values.deployment.restartPolicy }}
  serviceAccountName: parasoft-account
{{- if .Values.image.pullSecret }}
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret }}
{{- end }}
