# The following is an example persistent volume template that uses the example persistence values in
# the "values.yaml". You may remove or modify the values and templates to fit your own deployment needs.
{{- if or (eq "hostpath" .Values.persistence.type) (eq "nfs" .Values.persistence.type) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dtp-pv
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  capacity:
    storage: {{ .Values.persistence.capacity }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
{{- if eq "hostpath" .Values.persistence.type }}
  hostPath:
    path: {{ .Values.hostpath.path }}
{{- end }}
{{- if eq "nfs" .Values.persistence.type }}
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
{{- end }}
{{- end }}